version: "3"
services:
  api:
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U" ,"${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
