version: "3"
services:
  api:
    image: basesvc
    build:
      context: ../.
      dockerfile: ./build/Dockerfile
    container_name: basesvc_api
    ports:
      - 9090:9090
    volumes: 
      - ../.:/app
